# Generated by Django 5.1.4 on 2025-05-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Принят'), ('ready', 'Готов к получению'), ('done', 'Выдан')], default='pending', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
