# Generated by Django 5.1.4 on 2025-05-18 18:13

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rich_specs',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Характеристики (rich)'),
        ),
    ]
