# Generated by Django 5.1.4 on 2025-05-25 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_productreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
