# Generated by Django 5.1.4 on 2025-05-31 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_product_color_remove_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcharacteristicvalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='значение_характеристики', to='main.product'),
        ),
    ]
